# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ f ]
  pull_request:
    branches: [ f ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build Index
      run: |
        python Build-Padma-Index.py
        gzip -9 Padma-Index.pkl
        git clone https://github.com/Lotus-King-Research/Padma-Index
        git checkout latest
        mv Padma-Index/Padma-Index.pkl.gz Padma-Index/Padma-Index-Previous.pkl.gz
        mv Padma-Index.pkl.gz Padma-Index/Padma-Index.pkl.gz
        cd Padma-Index
        git add --all
        git commit -m "latest index build"
        git push
